
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 29 21:25:11 EST 2019
//----------------------------------------------------

package fnplot.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOL = 50;
  public static final int READ = 44;
  public static final int HEX = 73;
  public static final int SEMI = 21;
  public static final int UNTIL = 58;
  public static final int COMMA = 20;
  public static final int RBRACE = 19;
  public static final int RPAREN = 3;
  public static final int POW = 14;
  public static final int CLEAR = 7;
  public static final int EQV = 32;
  public static final int INTEGER = 65;
  public static final int LBRACE = 18;
  public static final int LPAREN = 2;
  public static final int LOGOP = 68;
  public static final int COMPARE = 67;
  public static final int UNI = 71;
  public static final int DEF = 37;
  public static final int READINT = 45;
  public static final int THEN = 39;
  public static final int PROC = 35;
  public static final int COMPAREEQUAL = 51;
  public static final int MUL = 10;
  public static final int PRINTLN = 43;
  public static final int EMPTY = 25;
  public static final int MOD = 12;
  public static final int CDR = 28;
  public static final int PLOT = 6;
  public static final int PLUS = 8;
  public static final int QUESTION = 29;
  public static final int WHILE = 59;
  public static final int EQUAL = 33;
  public static final int ASSIGN = 13;
  public static final int CHAR = 70;
  public static final int DO = 60;
  public static final int DELETEMIN = 54;
  public static final int VARIABLE = 66;
  public static final int FOR = 56;
  public static final int MAPS = 5;
  public static final int DIV = 11;
  public static final int CONCAT = 46;
  public static final int ELSE = 40;
  public static final int PAIRQ = 34;
  public static final int FUN = 4;
  public static final int EOF = 0;
  public static final int BIN = 72;
  public static final int GETMIN = 53;
  public static final int PRINT = 42;
  public static final int HEAPIFY = 52;
  public static final int REPEAT = 57;
  public static final int MINUS = 15;
  public static final int LVEC = 47;
  public static final int IN = 17;
  public static final int error = 1;
  public static final int PAIR = 26;
  public static final int LIST = 30;
  public static final int IF = 38;
  public static final int LSQR = 23;
  public static final int END = 62;
  public static final int COLON = 22;
  public static final int SUBTRACT = 9;
  public static final int BEGIN = 61;
  public static final int CASE = 41;
  public static final int RVEC = 48;
  public static final int INSERT = 55;
  public static final int STRING = 69;
  public static final int SIZE = 31;
  public static final int RANGE = 64;
  public static final int CAR = 27;
  public static final int TO = 63;
  public static final int SUBSTR = 49;
  public static final int RSQR = 24;
  public static final int LET = 16;
  public static final int CALL = 36;
}

