
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 29 06:12:51 EST 2019
//----------------------------------------------------

package fnplot.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LVEC = 48;
  public static final int POW = 15;
  public static final int CHAR = 62;
  public static final int COMPAREEQUAL = 52;
  public static final int CONCAT = 47;
  public static final int MAPS = 5;
  public static final int EMPTY = 26;
  public static final int READINT = 46;
  public static final int CASE = 42;
  public static final int CAR = 28;
  public static final int SUBTRACT = 10;
  public static final int INTEGER = 57;
  public static final int CDR = 29;
  public static final int LPAREN = 2;
  public static final int SEMI = 22;
  public static final int HEX = 65;
  public static final int PRINTLN = 44;
  public static final int FOR = 8;
  public static final int MINUS = 16;
  public static final int RPAREN = 3;
  public static final int LSQR = 24;
  public static final int FUN = 4;
  public static final int IN = 18;
  public static final int BOOL = 51;
  public static final int COMMA = 21;
  public static final int CALL = 37;
  public static final int PLOT = 6;
  public static final int DIV = 12;
  public static final int PLUS = 9;
  public static final int IF = 39;
  public static final int ASSIGN = 14;
  public static final int RVEC = 49;
  public static final int EOF = 0;
  public static final int EQUAL = 34;
  public static final int SIZE = 32;
  public static final int error = 1;
  public static final int MUL = 11;
  public static final int MOD = 13;
  public static final int HEAPIFY = 53;
  public static final int PAIR = 27;
  public static final int GETMIN = 54;
  public static final int EQV = 33;
  public static final int COMPARE = 59;
  public static final int COLON = 23;
  public static final int BIN = 64;
  public static final int ELSE = 41;
  public static final int LBRACE = 19;
  public static final int PAIRQ = 35;
  public static final int VARIABLE = 58;
  public static final int READ = 45;
  public static final int RSQR = 25;
  public static final int INSERT = 56;
  public static final int LIST = 31;
  public static final int LOGOP = 60;
  public static final int SUBSTR = 50;
  public static final int LET = 17;
  public static final int CLEAR = 7;
  public static final int THEN = 40;
  public static final int RBRACE = 20;
  public static final int STRING = 61;
  public static final int PROC = 36;
  public static final int QUESTION = 30;
  public static final int DEF = 38;
  public static final int UNI = 63;
  public static final int DELETEMIN = 55;
  public static final int PRINT = 43;
}

