
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 27 05:51:43 EST 2019
//----------------------------------------------------

package fnplot.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LVEC = 47;
  public static final int POW = 15;
  public static final int CHAR = 55;
  public static final int CONCAT = 46;
  public static final int MAPS = 5;
  public static final int EMPTY = 26;
  public static final int READINT = 45;
  public static final int CASE = 41;
  public static final int CAR = 28;
  public static final int SUBTRACT = 10;
  public static final int INTEGER = 50;
  public static final int CDR = 29;
  public static final int LPAREN = 2;
  public static final int SEMI = 22;
  public static final int HEX = 58;
  public static final int PRINTLN = 43;
  public static final int FOR = 8;
  public static final int MINUS = 16;
  public static final int RPAREN = 3;
  public static final int LSQR = 24;
  public static final int FUN = 4;
  public static final int IN = 18;
  public static final int BOOL = 59;
  public static final int COMMA = 21;
  public static final int CALL = 36;
  public static final int PLOT = 6;
  public static final int DIV = 12;
  public static final int PLUS = 9;
  public static final int IF = 38;
  public static final int ASSIGN = 14;
  public static final int RVEC = 48;
  public static final int EOF = 0;
  public static final int EQUAL = 34;
  public static final int SIZE = 32;
  public static final int error = 1;
  public static final int MUL = 11;
  public static final int MOD = 13;
  public static final int PAIR = 27;
  public static final int EQV = 33;
  public static final int COMPARE = 52;
  public static final int COLON = 23;
  public static final int BIN = 57;
  public static final int ELSE = 40;
  public static final int LBRACE = 19;
  public static final int VARIABLE = 51;
  public static final int READ = 44;
  public static final int RSQR = 25;
  public static final int LIST = 31;
  public static final int LOGOP = 53;
  public static final int SUBSTR = 49;
  public static final int LET = 17;
  public static final int CLEAR = 7;
  public static final int THEN = 39;
  public static final int RBRACE = 20;
  public static final int STRING = 54;
  public static final int PROC = 35;
  public static final int QUESTION = 30;
  public static final int DEF = 37;
  public static final int UNI = 56;
  public static final int PRINT = 42;
}

