
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 22 22:04:31 EST 2019
//----------------------------------------------------

package fnplot.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 15;
  public static final int CONCAT = 49;
  public static final int MAPS = 5;
  public static final int EMPTY = 29;
  public static final int READINT = 48;
  public static final int CASE = 44;
  public static final int CAR = 31;
  public static final int INTEGER = 50;
  public static final int CDR = 32;
  public static final int LPAREN = 2;
  public static final int SEMI = 21;
  public static final int PRINTLN = 46;
  public static final int HEX = 26;
  public static final int FOR = 8;
  public static final int MINUS = 10;
  public static final int RPAREN = 3;
  public static final int LSQR = 23;
  public static final int FUN = 4;
  public static final int IN = 17;
  public static final int BOOL = 28;
  public static final int COMMA = 20;
  public static final int CALL = 39;
  public static final int PLOT = 6;
  public static final int DIV = 12;
  public static final int PLUS = 9;
  public static final int IF = 41;
  public static final int ASSIGN = 14;
  public static final int EOF = 0;
  public static final int EQUAL = 37;
  public static final int SIZE = 35;
  public static final int error = 1;
  public static final int MUL = 11;
  public static final int MOD = 13;
  public static final int PAIR = 30;
  public static final int EQV = 36;
  public static final int COLON = 22;
  public static final int ELSE = 43;
  public static final int BIN = 25;
  public static final int LBRACE = 18;
  public static final int VARIABLE = 51;
  public static final int READ = 47;
  public static final int RSQR = 24;
  public static final int LIST = 34;
  public static final int LET = 16;
  public static final int CLEAR = 7;
  public static final int THEN = 42;
  public static final int RBRACE = 19;
  public static final int PROC = 38;
  public static final int QUESTION = 33;
  public static final int DEF = 40;
  public static final int UNI = 27;
  public static final int PRINT = 45;
}

