/* The following code was generated by JFlex 1.6.1 */

package fnplot.syntax;

/* Specification for ArithExp tokens */

// user customisations
import java_cup.runtime.*;

// Jlex directives

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>FnPlotLexer</tt>
 */
public class FnPlotLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\2\1\2\1\1\1\0\1\2\1\1\22\0\1\2\2\0"+
    "\1\44\1\0\1\11\2\0\1\15\1\16\1\7\1\5\1\21\1\6"+
    "\1\60\1\10\2\46\10\4\1\43\1\57\1\0\1\12\1\33\1\52"+
    "\1\14\6\50\24\3\1\41\1\0\1\42\1\13\1\3\1\0\1\26"+
    "\1\45\1\36\1\51\1\37\1\22\1\3\1\56\1\40\2\3\1\34"+
    "\1\25\1\24\1\32\1\27\1\54\1\35\1\30\1\31\1\23\1\55"+
    "\1\3\1\47\1\3\1\53\1\17\1\0\1\20\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\0\1\5\1\6"+
    "\1\7\1\10\1\11\12\3\1\12\1\13\1\14\1\0"+
    "\1\3\1\15\1\16\10\0\1\17\1\20\20\3\1\21"+
    "\1\22\1\23\1\24\1\25\1\0\1\26\1\27\2\0"+
    "\1\3\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\7\3\1\42\4\3\1\43\1\3"+
    "\1\44\2\3\1\45\1\0\1\46\1\47\1\50\1\3"+
    "\1\51\1\52\1\53\1\3\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\3\1\62\1\3\1\0\1\46\1\47"+
    "\1\3\1\63\1\3\1\64\1\65\1\0\1\46\1\47"+
    "\1\20\2\3\1\66\1\46\1\47\1\67\1\70\1\46"+
    "\1\47\1\46\1\47\1\46\1\47\1\46\1\47\30\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\61\0\142\0\223\0\304\0\365\0\365"+
    "\0\365\0\365\0\365\0\u0126\0\u0157\0\u0188\0\u01b9\0\u01ea"+
    "\0\u021b\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\365\0\u0341"+
    "\0\u0372\0\u03a3\0\365\0\365\0\u03d4\0\u0405\0\u0436\0\u0467"+
    "\0\u0498\0\u04c9\0\u04fa\0\u052b\0\u055c\0\365\0\u058d\0\u05be"+
    "\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0746"+
    "\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c\0\142\0\142"+
    "\0\365\0\365\0\365\0\u089d\0\365\0\365\0\u08ce\0\u08ff"+
    "\0\u0930\0\365\0\365\0\365\0\365\0\365\0\365\0\365"+
    "\0\365\0\142\0\142\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25"+
    "\0\u0a56\0\u0a87\0\142\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\142"+
    "\0\u0b7c\0\142\0\u0bad\0\u0bde\0\142\0\u0c0f\0\u0c40\0\u0c71"+
    "\0\142\0\u0ca2\0\142\0\142\0\142\0\u0cd3\0\142\0\142"+
    "\0\142\0\u0d04\0\142\0\142\0\u0d35\0\142\0\u0d66\0\u0d97"+
    "\0\u0dc8\0\u0df9\0\u0e2a\0\u0e5b\0\u0e8c\0\142\0\142\0\u0ebd"+
    "\0\u0eee\0\u0f1f\0\142\0\u0f50\0\u0f81\0\365\0\u0fb2\0\u0fe3"+
    "\0\142\0\142\0\u1014\0\u1045\0\u1076\0\u10a7\0\u10d8\0\u1109"+
    "\0\u113a\0\365\0\u116b\0\u119c\0\u11cd\0\u11fe\0\u122f\0\u1260"+
    "\0\u1291\0\u12c2\0\u12f3\0\u1324\0\u1355\0\u1386\0\u13b7\0\u13e8"+
    "\0\u1419\0\u144a\0\u147b\0\u14ac\0\u14dd\0\u150e\0\u153f\0\u1570"+
    "\0\u15a1\0\365";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\5\1\0\1\6\6\0"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\2\4\1\15"+
    "\1\4\1\16\1\17\1\20\1\4\1\0\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\4"+
    "\1\5\2\4\1\32\1\33\4\4\1\34\6\0\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\47\0"+
    "\2\4\15\0\11\4\1\0\5\4\4\0\5\4\1\0"+
    "\4\4\6\0\1\5\41\0\1\5\11\0\1\45\33\0"+
    "\1\46\111\0\2\4\15\0\1\4\1\47\6\4\1\50"+
    "\1\0\5\4\4\0\5\4\1\0\4\4\5\0\2\4"+
    "\15\0\4\4\1\51\4\4\1\0\5\4\4\0\5\4"+
    "\1\0\4\4\5\0\2\4\15\0\4\4\1\52\4\4"+
    "\1\0\1\53\1\54\3\4\4\0\5\4\1\0\4\4"+
    "\5\0\2\4\15\0\11\4\1\0\4\4\1\55\4\0"+
    "\5\4\1\0\4\4\5\0\2\4\15\0\11\4\1\0"+
    "\5\4\4\0\5\4\1\0\3\4\1\56\5\0\2\4"+
    "\15\0\11\4\1\0\3\4\1\57\1\60\4\0\5\4"+
    "\1\0\4\4\5\0\2\4\15\0\11\4\1\0\3\4"+
    "\1\61\1\4\4\0\5\4\1\0\4\4\5\0\2\4"+
    "\15\0\4\4\1\62\4\4\1\0\1\63\4\4\4\0"+
    "\4\4\1\64\1\0\4\4\5\0\2\4\15\0\11\4"+
    "\1\0\1\65\4\4\4\0\5\4\1\0\1\4\1\66"+
    "\2\4\5\0\2\4\15\0\1\67\1\4\1\70\6\4"+
    "\1\0\5\4\4\0\5\4\1\0\4\4\45\0\1\71"+
    "\57\0\1\72\40\0\1\73\1\74\5\0\1\75\5\0"+
    "\1\76\5\0\1\77\1\0\1\100\14\0\2\4\15\0"+
    "\11\4\1\0\3\4\1\101\1\4\4\0\5\4\1\0"+
    "\4\4\3\0\2\102\57\0\2\103\57\0\2\104\57\0"+
    "\2\105\57\0\2\106\57\0\2\107\57\0\2\110\57\0"+
    "\2\111\62\0\1\45\41\0\1\45\15\0\2\4\15\0"+
    "\2\4\1\112\6\4\1\0\5\4\4\0\5\4\1\0"+
    "\4\4\5\0\2\4\15\0\11\4\1\0\1\4\1\113"+
    "\3\4\4\0\5\4\1\0\4\4\5\0\2\4\15\0"+
    "\5\4\1\114\3\4\1\0\5\4\4\0\5\4\1\0"+
    "\4\4\5\0\2\4\15\0\11\4\1\0\4\4\1\115"+
    "\4\0\5\4\1\0\4\4\5\0\2\4\15\0\10\4"+
    "\1\116\1\0\5\4\4\0\5\4\1\0\4\4\5\0"+
    "\2\4\15\0\10\4\1\117\1\0\4\4\1\120\4\0"+
    "\5\4\1\0\4\4\5\0\2\4\15\0\11\4\1\0"+
    "\5\4\4\0\5\4\1\0\1\121\3\4\5\0\2\4"+
    "\15\0\11\4\1\0\3\4\1\122\1\4\4\0\5\4"+
    "\1\0\4\4\5\0\2\4\15\0\7\4\1\123\1\4"+
    "\1\0\5\4\4\0\5\4\1\0\4\4\5\0\2\4"+
    "\15\0\6\4\1\124\2\4\1\0\5\4\4\0\5\4"+
    "\1\0\4\4\5\0\2\4\15\0\4\4\1\125\4\4"+
    "\1\0\5\4\4\0\5\4\1\0\4\4\5\0\2\4"+
    "\15\0\6\4\1\126\2\4\1\0\1\127\1\130\3\4"+
    "\4\0\5\4\1\0\4\4\5\0\2\4\15\0\11\4"+
    "\1\0\3\4\1\131\1\4\4\0\5\4\1\0\4\4"+
    "\5\0\2\4\15\0\11\4\1\0\1\4\1\132\3\4"+
    "\4\0\5\4\1\0\4\4\5\0\2\4\15\0\6\4"+
    "\1\133\2\4\1\0\5\4\4\0\5\4\1\0\4\4"+
    "\5\0\2\4\15\0\1\4\1\134\7\4\1\0\5\4"+
    "\4\0\5\4\1\0\2\4\1\135\1\4\6\0\1\136"+
    "\15\0\1\136\3\0\1\136\7\0\2\136\5\0\2\136"+
    "\1\0\2\136\55\0\1\137\16\0\1\140\15\0\1\140"+
    "\3\0\1\140\7\0\2\140\5\0\2\140\1\0\2\140"+
    "\12\0\2\4\15\0\1\141\10\4\1\0\5\4\4\0"+
    "\5\4\1\0\4\4\5\0\2\4\15\0\6\4\1\142"+
    "\2\4\1\0\5\4\4\0\5\4\1\0\4\4\5\0"+
    "\2\4\15\0\11\4\1\0\1\4\1\143\3\4\4\0"+
    "\5\4\1\0\4\4\5\0\2\4\15\0\7\4\1\144"+
    "\1\4\1\0\5\4\4\0\5\4\1\0\4\4\5\0"+
    "\2\4\15\0\11\4\1\0\2\4\1\145\2\4\4\0"+
    "\5\4\1\0\4\4\5\0\2\4\15\0\2\4\1\146"+
    "\6\4\1\0\5\4\4\0\5\4\1\0\4\4\5\0"+
    "\2\4\15\0\11\4\1\0\3\4\1\147\1\4\4\0"+
    "\5\4\1\0\4\4\5\0\2\4\15\0\2\4\1\150"+
    "\6\4\1\0\5\4\4\0\5\4\1\0\4\4\5\0"+
    "\2\4\15\0\7\4\1\151\1\4\1\0\5\4\4\0"+
    "\5\4\1\0\4\4\5\0\2\4\15\0\11\4\1\0"+
    "\5\4\4\0\4\4\1\152\1\0\4\4\5\0\2\4"+
    "\15\0\11\4\1\0\3\4\1\153\1\4\4\0\5\4"+
    "\1\0\4\4\5\0\2\4\15\0\11\4\1\0\1\154"+
    "\4\4\4\0\5\4\1\0\4\4\5\0\2\4\15\0"+
    "\4\4\1\155\4\4\1\0\5\4\4\0\5\4\1\0"+
    "\4\4\5\0\2\4\15\0\11\4\1\0\3\4\1\156"+
    "\1\4\4\0\5\4\1\0\4\4\5\0\2\4\15\0"+
    "\4\4\1\157\4\4\1\0\5\4\4\0\5\4\1\0"+
    "\4\4\6\0\1\160\15\0\1\160\3\0\1\160\7\0"+
    "\2\160\5\0\2\160\1\0\2\160\55\0\1\161\16\0"+
    "\1\162\15\0\1\162\3\0\1\162\7\0\2\162\5\0"+
    "\2\162\1\0\2\162\12\0\2\4\15\0\7\4\1\163"+
    "\1\4\1\0\5\4\4\0\5\4\1\0\4\4\5\0"+
    "\2\4\15\0\7\4\1\164\1\4\1\0\5\4\4\0"+
    "\5\4\1\0\4\4\5\0\2\4\15\0\11\4\1\0"+
    "\4\4\1\165\4\0\5\4\1\0\4\4\5\0\2\4"+
    "\15\0\11\4\1\0\1\4\1\166\3\4\4\0\5\4"+
    "\1\0\4\4\5\0\2\4\15\0\11\4\1\0\1\167"+
    "\4\4\4\0\5\4\1\0\4\4\6\0\1\170\15\0"+
    "\1\170\3\0\1\170\7\0\2\170\5\0\2\170\1\0"+
    "\2\170\55\0\1\171\16\0\1\172\15\0\1\172\3\0"+
    "\1\172\7\0\2\172\5\0\2\172\1\0\2\172\12\0"+
    "\2\4\15\0\10\4\1\173\1\0\5\4\4\0\5\4"+
    "\1\0\4\4\5\0\2\4\15\0\11\4\1\0\1\174"+
    "\4\4\4\0\5\4\1\0\4\4\5\0\2\4\15\0"+
    "\2\4\1\175\6\4\1\0\5\4\4\0\5\4\1\0"+
    "\4\4\6\0\1\176\15\0\1\176\3\0\1\176\7\0"+
    "\2\176\5\0\2\176\1\0\2\176\55\0\1\177\16\0"+
    "\1\200\15\0\1\200\3\0\1\200\7\0\2\200\5\0"+
    "\2\200\1\0\2\200\12\0\2\4\15\0\2\4\1\201"+
    "\6\4\1\0\5\4\4\0\5\4\1\0\4\4\5\0"+
    "\2\4\15\0\7\4\1\202\1\4\1\0\5\4\4\0"+
    "\5\4\1\0\4\4\50\0\1\203\16\0\1\204\15\0"+
    "\1\204\3\0\1\204\7\0\2\204\5\0\2\204\1\0"+
    "\2\204\55\0\1\205\16\0\1\206\15\0\1\206\3\0"+
    "\1\206\7\0\2\206\5\0\2\206\1\0\2\206\55\0"+
    "\1\207\16\0\1\210\15\0\1\210\3\0\1\210\7\0"+
    "\2\210\5\0\2\210\1\0\2\210\55\0\1\211\16\0"+
    "\1\212\15\0\1\212\3\0\1\212\7\0\2\212\5\0"+
    "\2\212\1\0\2\212\55\0\1\213\60\0\1\214\60\0"+
    "\1\215\60\0\1\216\60\0\1\217\60\0\1\220\60\0"+
    "\1\221\60\0\1\222\60\0\1\223\60\0\1\224\60\0"+
    "\1\225\60\0\1\226\60\0\1\227\60\0\1\230\60\0"+
    "\1\231\60\0\1\232\60\0\1\233\60\0\1\234\60\0"+
    "\1\235\60\0\1\236\60\0\1\237\60\0\1\240\60\0"+
    "\1\241\60\0\1\242\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5586];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\4\1\1\0\5\11\13\1\1\11\1\1\1\0"+
    "\1\1\2\11\10\0\1\1\1\11\22\1\3\11\1\0"+
    "\2\11\2\0\1\1\10\11\24\1\1\0\21\1\1\0"+
    "\7\1\1\0\5\1\1\11\13\1\1\11\27\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public int getChar() {
	return yychar + 1;
    }

    public int getColumn() {
    	return yycolumn + 1;
    }

    public int getLine() {
	return yyline + 1;
    }

    public String getText() {
	return yytext();
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FnPlotLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	return new Symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { //skip newline, but reset char counter
			yycolumn = 0;
            }
          case 57: break;
          case 2: 
            { //skip whitespace
            }
          case 58: break;
          case 3: 
            { // VARIABLE
	       return new Symbol(sym.VARIABLE, yytext());
            }
          case 59: break;
          case 4: 
            { // INTEGER
	       return new Symbol(sym.INTEGER, 
				 new Double(yytext()));
            }
          case 60: break;
          case 5: 
            { return new Symbol(sym.LPAREN);
            }
          case 61: break;
          case 6: 
            { return new Symbol(sym.RPAREN);
            }
          case 62: break;
          case 7: 
            { return new Symbol(sym.LBRACE);
            }
          case 63: break;
          case 8: 
            { return new Symbol(sym.RBRACE);
            }
          case 64: break;
          case 9: 
            { return new Symbol(sym.COMMA);
            }
          case 65: break;
          case 10: 
            { return new Symbol(sym.LSQR);
            }
          case 66: break;
          case 11: 
            { return new Symbol(sym.RSQR);
            }
          case 67: break;
          case 12: 
            { return new Symbol(sym.COLON);
            }
          case 68: break;
          case 13: 
            { return new Symbol(sym.QUESTION);
            }
          case 69: break;
          case 14: 
            { return new Symbol(sym.SEMI);
            }
          case 70: break;
          case 15: 
            { // FLOAT
	       return new Symbol(sym.INTEGER, 
				 new Double(yytext()));
            }
          case 71: break;
          case 16: 
            { return new Symbol(sym.MAPS);
            }
          case 72: break;
          case 17: 
            { return new Symbol(sym.IF);
            }
          case 73: break;
          case 18: 
            { return new Symbol(sym.IN);
            }
          case 74: break;
          case 19: 
            { return new Symbol(sym.LVEC);
            }
          case 75: break;
          case 20: 
            { return new Symbol(sym.RVEC);
            }
          case 76: break;
          case 21: 
            { return new Symbol(sym.BOOL, new Boolean(false));
            }
          case 77: break;
          case 22: 
            { return new Symbol(sym.BOOL, new Boolean(true));
            }
          case 78: break;
          case 23: 
            { return new Symbol(sym.EMPTY);
            }
          case 79: break;
          case 24: 
            { return new Symbol(sym.PLUS);
            }
          case 80: break;
          case 25: 
            { return new Symbol(sym.MINUS);
            }
          case 81: break;
          case 26: 
            { return new Symbol(sym.MUL);
            }
          case 82: break;
          case 27: 
            { return new Symbol(sym.DIV);
            }
          case 83: break;
          case 28: 
            { return new Symbol(sym.MOD);
            }
          case 84: break;
          case 29: 
            { return new Symbol(sym.ASSIGN);
            }
          case 85: break;
          case 30: 
            { return new Symbol(sym.POW);
            }
          case 86: break;
          case 31: 
            { return new Symbol(sym.CONCAT);
            }
          case 87: break;
          case 32: 
            { return new Symbol(sym.FUN);
            }
          case 88: break;
          case 33: 
            { return new Symbol(sym.FOR);
            }
          case 89: break;
          case 34: 
            { return new Symbol(sym.LET);
            }
          case 90: break;
          case 35: 
            { return new Symbol(sym.CAR);
            }
          case 91: break;
          case 36: 
            { return new Symbol(sym.CDR);
            }
          case 92: break;
          case 37: 
            { return new Symbol(sym.EQV);
            }
          case 93: break;
          case 38: 
            { return new Symbol(sym.BIN, yytext());
            }
          case 94: break;
          case 39: 
            { return new Symbol(sym.HEX, yytext());
            }
          case 95: break;
          case 40: 
            { return new Symbol(sym.DEF);
            }
          case 96: break;
          case 41: 
            { return new Symbol(sym.PAIR);
            }
          case 97: break;
          case 42: 
            { return new Symbol(sym.PLOT);
            }
          case 98: break;
          case 43: 
            { return new Symbol(sym.PROC);
            }
          case 99: break;
          case 44: 
            { return new Symbol(sym.SIZE);
            }
          case 100: break;
          case 45: 
            { return new Symbol(sym.THEN);
            }
          case 101: break;
          case 46: 
            { return new Symbol(sym.LIST);
            }
          case 102: break;
          case 47: 
            { return new Symbol(sym.READ);
            }
          case 103: break;
          case 48: 
            { return new Symbol(sym.CASE);
            }
          case 104: break;
          case 49: 
            { return new Symbol(sym.CALL);
            }
          case 105: break;
          case 50: 
            { return new Symbol(sym.ELSE);
            }
          case 106: break;
          case 51: 
            { return new Symbol(sym.PRINT);
            }
          case 107: break;
          case 52: 
            { return new Symbol(sym.CLEAR);
            }
          case 108: break;
          case 53: 
            { return new Symbol(sym.EQUAL);
            }
          case 109: break;
          case 54: 
            { return new Symbol(sym.UNI, yytext());
            }
          case 110: break;
          case 55: 
            { return new Symbol(sym.PRINTLN);
            }
          case 111: break;
          case 56: 
            { return new Symbol(sym.READINT);
            }
          case 112: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
